force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Course_image__c.field-meta.xml
<CustomField>
    <fullName>Course_image__c</fullName>
    <label>Course image</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Course_Assignment__c/Course_Assignment__c.object-meta.xml
<CustomObject>
    <label>Course Assignment</label>
    <nameField>
        <label>CourseAssignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Assignment__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Assignments</relationshipLabel>
    <relationshipName>Course_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Assignment__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Course_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CourseService.cls
public with sharing class CourseService {
    public class CourseModel {
        @AuraEnabled public String id { get; set; }
        @AuraEnabled public String name { get; set; }
        @AuraEnabled public String description { get; set; }
        @AuraEnabled public String imageUrl { get; set; }

        private CourseModel(Course__c c) {
            id = c.Id;
            name = c.Name;
            description = c.Description__c;
            imageUrl = c.Course_image__c;
        }
    }

    public class CourseAssignmentModel {
        @AuraEnabled public String id { get; set; }
        @AuraEnabled public String assignmentId { get; set; }
        @AuraEnabled public String name { get; set; }
        @AuraEnabled public String description { get; set; }
        @AuraEnabled public String imageUrl { get; set; }
        @AuraEnabled public String status { get; set; }
        @AuraEnabled public String score { get; set; }

        private CourseAssignmentModel(Course_Assignment__c assignment) {
            id = assignment.Course__r.Id;
            assignmentId = assignment.Id;
            name = assignment.Course__r.Name;
            description = assignment.Course__r.Description__c;
            imageUrl = assignment.Course__r.Course_image__c;
            status = assignment.Status__c;
            score = assignment.Score__c != null ? String.valueOf(assignment.Score__c) : null;
        }
    }

    public static List<CourseModel> mapToModelCourse(List<Course__c> courses) {
        List<CourseModel> result = new List<CourseModel>();
        for (Course__c c : courses) {
            result.add(new CourseModel(c));
        }
        return result;
    }

    public static List<CourseAssignmentModel> mapToModelCourseAssignment(List<Course_Assignment__c> assignments) {
        List<CourseAssignmentModel> result = new List<CourseAssignmentModel>();
        for (Course_Assignment__c assignment : assignments) {
            result.add(new CourseAssignmentModel(assignment));
        }
        return result;
    }

    public static List<CourseModel> getCourses() {
        List<Course__c> records = LearningSelector.getCourses();
        return mapToModelCourse(records);
    }

    public static List<CourseAssignmentModel> getMyCourses() {
        List<Course_Assignment__c> records = LearningSelector.getMyCourses(UserInfo.getUserId());
        return mapToModelCourseAssignment(records);
    }

    public static Boolean isCourseAdmin() {
        return LearningSelector.isCourseAdmin(UserInfo.getUserId());
    }

}